profile: full

shared:
  ingress_domain: tap-on-eks.tanzulab.io

ceip_policy_disclosed: TRUE
buildservice:
  kp_default_repository: "index.docker.io/powellcrack/build-service"
  kp_default_repository_username: "powellcrack"
  kp_default_repository_password: "Qh#!3#ocuYDlq0th"
  tanzunet_username: "xinstevenl@vmware.com"
  tanzunet_password: "#Dr34mJ0b#"
  descriptor_name: "full"

supply_chain: basic

cnrs:
  domain_name: tap-on-eks.tanzulab.io

ootb_supply_chain_basic:
  registry:
    server: "index.docker.io"
    repository: "powellcrack/supply-chain"
  gitops:
    ssh_secret: "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"

learningcenter:
  ingressDomain: learningcenter.tap-on-eks.tanzulab.io
  ingressClass: contour


tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: tap-on-eks.tanzulab.io
  app_config:
    app:
      baseUrl: http://tap-gui.tap-on-eks.tanzulab.io
    catalog:
      locations:
        - type: url
          target: https://raw.githubusercontent.com/bullblock/tap.tanzulab.io/main/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.tap-on-eks.tanzulab.io
      cors:
        origin: http://tap-gui.tap-on-eks.tanzulab.io

metadata_store:
  ns_for_export_app_cert: "default"
  app_service_type: ClusterIP

grype:
  namespace: "default"
  targetImagePullSecret: "tap-registry"

accelerator:
  server:
    service_type: "ClusterIP"

contour:
  infrastructure_provider: aws
  envoy:
    service:
      aws:
        LBType: nlb
