profile: full
ceip_policy_disclosed: "true" # The value must be true for installation to succeed
buildservice:
  kp_default_repository: "dev.registry.tanzu.vmware.com/sliang/build-service"
  kp_default_repository_username: "xinstevenl@vmware.com"
  kp_default_repository_password: '$Dr34mJ0b$'
  tanzunet_username: "xinstevenl@vmware.com"
  tanzunet_password: '$Dr34mJ0b$'
  descriptor_name: "full"
supply_chain: basic

cnrs:
  domain_name: "tap.tanzulab.io"

ootb_supply_chain_basic:
  registry:
    server: "dev.registry.tanzu.vmware.com"
    repository: "sliang/supply-chain"
  gitops:
    ssh_secret: ""

learningcenter:
  ingressDomain: "learningcenter.tap.tanzulab.io"

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "tap.tanzulab.io"
  app_config:
    app:
      baseUrl: http://tap-gui.tap.tanzulab.io
    catalog:
      locations:
        - type: url
          target: https://raw.githubusercontent.com/bullblock/tap.tanzulab.io/main/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.tap.tanzulab.io
      cors:
        origin: http://tap-gui.tap.tanzulab.io

metadata_store:
  app_service_type: NodePort # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

grype:
  namespace: "default" # (optional) Defaults to default namespace.
  targetImagePullSecret: "tap-registry"

accelerator:
  server:
    service_type: "ClusterIP"

contour:
  infrastructure_provider: aws
  envoy:
    service:
      aws:
        LBType: nlb
